name: 'Update iOS Plist'
description: 'Update iOS User Defined keys in your Info.plist file'
author: 'damienaicheh'
inputs:
  info-plist-path:
    description: 'Relative path for the Info.plist file.'
    required: true
  bundle-identifier:
    description: 'The value of the CF Bundle Identifier'
    required: true
  bundle-name:
    description: 'The value of the CF Bundle Name'
    required: false
  bundle-display-name:
    description: 'he value of the CF Bundle Display Name'
    required: false
  print-file:
    description: 'Output the Info.plist file in console'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'file'
  color: 'blue'
