name: 'Update iOS Plist'
description: 'Update iOS User Defined keys in your Info.plist file'
author: 'dppeak'
inputs:
  info-plist-path:
    description: 'Relative path for the Info.plist file.'
    required: true
  key-name:
    description: 'The name of the user defined key'
    required: true
  key-value:
    description: 'The value of the user defined key'
    required: true
  print-file:
    description: 'Output the Info.plist file in console'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'file'
  color: 'blue'
