name: sample

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  demo:
    runs-on: macos-latest
    name: Sample demo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Bundle identifier
        uses: dppeak/update-ios-plist-action@v1.0.0
        with:
          info-plist-path: './samples/Info.plist'
          key-name: 'UserCustomKey'
          key-value: 'Some Value to store'
          print-file: true
