name: versions

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  local-version:
    runs-on: macos-latest
    name: Run local action version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update iOS Info.plist
        uses: ./
        with:
          info-plist-path: './samples/Info.plist'
          key-name: 'UserCustomKey'
          key-value: 'Some Value to store'
          print-file: true